name: visual-odometry
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - icu=78.1
  - ld_impl_linux-64=2.45
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.3
  - python=3.11.14
  - readline=8.3
  - setuptools=80.9.0
  - tk=8.6.13
  - tzdata=2025c
  - wheel=0.45.1
  - zstd=1.5.7
  - pip:
      - attrs==25.4.0
      - cfgv==3.5.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - distlib==0.4.0
      - docstring-parser==0.17.0
      - filelock==3.20.2
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - identify==2.6.15
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - lightglue==0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - networkx==3.6.1
      - nodeenv==1.10.0
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pillow==12.1.0
      - platformdirs==4.5.1
      - pre-commit==4.5.1
      - pyarrow==22.0.0
      - pyceres==2.6
      - pycolmap==3.13.0
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - rerun-sdk==0.28.1
      - scipy==1.16.3
      - six==1.17.0
      - sympy==1.14.0
      - torch==2.9.1
      - torchvision==0.24.1
      - triton==3.5.1
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - tyro==1.0.3
      - virtualenv==20.35.4
